### ISSUE TITLE
Copyright information

### ISSUE THREAD

**Issue by mikeferguson** [ros-perception/pcl_conversions#11]
@wjwwood What is the legacy of this code? My understanding is that these functions were copied in from PCL code that was removed, correct? If so, shouldn't the copyright retain "2010-2012 Willow Garage" in the line right below "2013 Open Source Robotics Foundation"?

**Comment by wjwwood** [comment]
The code was definitely inspired by the PCL code, but mostly it is new code.

Some parts where copied from ROS and modified, other parts were copied from PCL and modified.

It would probably be accurate to include the copyright WG, but mostly because of inspiration and copy and then modify. I don't think any of it is just copied without changes.

**Comment by mikeferguson** [comment]
@wjwwood, how would you want to handle code that is completely copied in from PCL? I'd like to open a pull request to import this function: https://github.com/mikeferguson/chessbox/blob/hydro-devel/chess_perception/include/chess_perception/conversions.h#L48 which I find I use a lot when subscribing to a point cloud and then wanting an image as well. Would you be ok with me adding the 2010-2012 WG line in the copyright header when adding that function?

**Comment by wjwwood** [comment]
I'm totally fine with that.

**Comment by wjwwood** [comment]
Can we close this?

**Comment by mikeferguson** [comment]
Yes we can.
