### ISSUE TITLE
toPCL timestamp precision loss makes exact time synchronization with pcl and ros message fail

### ISSUE THREAD

**Issue by lucasw** [ros-perception/pcl_conversions#23]
A message may get converted to pcl format timestamp microseconds, and then back to ros nanoseconds, but digits are lost in the process.  Is there a way (maybe involving changes beyond this library) to keep the original timestamp outside of the pcl header and restore it to the converted ros message before publication?

Should I instead have a publisher be sensor_msgs::PointCloud2 publisher instead of pcl::PointCloud<>, and convert the pcl cloud to the PointCloud2 format and force the timestamp to be what I want?

**Comment by wjwwood** [comment]
Yeah, unfortunately since PCL choose to use microseconds for their time rather than nanoseconds as we do in ROS 1, you'll either have to avoid the PCL types in pub/sub or communicate the time separately. There's not much of anything we can do about it, especially when this conversion API is being used implicitly in the publishing/subscribing pipeline.
