### ISSUE TITLE
Release into Melodic

### ISSUE THREAD

**Issue by clalancette** [ros-perception/pcl_conversions#28]
It looks like all of the dependencies of this are available in Melodic, so it would be great to get this released.  Thanks in advance!

**Comment by clalancette** [comment]
Ping?   Can we get this released into Melodic, please?  Thanks.

**Comment by wkentaro** [comment]
@paulbovbel Could you please work on this? This is necessary for the release of `perception_pcl`.

**Comment by paulbovbel** [comment]
Thanks for reminding me, I'll make it happen by this weekend

@wkentaro would you like to be a maintainer on this project as well?

It may actually make sense just to move this package into the pcl_ros repo. @clalancette, any reason why that would be a bad idea?

**Comment by wkentaro** [comment]
I'm not willing to both maintaining `pcl_conversions` and `perception_pcl` if they are separated,
since it takes time for me to keep watching both repositories to maintain.
So that would be better if `pcl_conversions` is moved to under the `perception_pcl` repository.

**Comment by clalancette** [comment]
> @clalancette, any reason why that would be a bad idea?

The general reason to maintain a split like this one is to have the library portion (pcl_conversions in this case) separate from the part that plugs it into ROS (perception_pcl/pcl_ros).  However, in this case it looks like both packages really require ROS, so that split may not be helping much.  @tfoote , @mikaelarguedas , can you think of other reasons why combining this repository and https://github.com/ros-perception/perception_pcl might be a bad idea?

**Comment by mikaelarguedas** [comment]
the main motivation in general is to allow people to reduce introducing circular dependencies between the repositories for releases. It also allows people to clone only what they need when they build from source rather than cloning a lot of maybe unrelated packages.

In this case, the packages seem tightly coupled and, as the metapackage is hosted on that repo, I think it makes sense to have the packages included in that metapackage in that repository as well.

Maybe @wjwwood that authored both pcl_ros and pcl_conversions has more context about why they were split in different repos in the first place

**Comment by wjwwood** [comment]
I believe the original reason was that `pcl_conversions` is needed to allow publishing and subscribing with PCL types, whereas `pcl_ros` has lots of built-in capabilities and nodelets, and if you don't need those things in `pcl_ros` you'd prefer not to have `pcl_ros` in your workspace (it's quite large and takes a long time to build).

You may combine them, though I don't feel that it gives you much benefit. My guess is that the work of properly merging the repositories (moving code while preserving history and migrating issues/pull requests and archiving this repository) will overshadow the time saved having one repository versus two.

So, it's ok to do it, but I don't recommend it.

**Comment by paulbovbel** [comment]
Thanks all. I think with the advent of catkin_tools, the cost of a local workspace having a blacklisted package you're not interested in is pretty small. I've actually been a fan of larger repos for internal development, since it cuts down on cross-repo PRs and makes the release cycle easier. Plus this way, I can get another maintainer's eyes (@wkentaro) on PRs and issues.

I've moved pcl_conversions into the melodic-devel branch of perception_pcl.
